name: calibratecpa
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  localpkg:
    git:
      url: https://github.com/Calebh101/localpkg-flutter
      ref: main

  path_provider: ^2.0.14
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.3
  auto_size_text: ^3.0.0
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/primary/calibrate.png

flutter_launcher_icons:
  image_path: "assets/icons/primary/calibrateFull.png"

  android: "launcher_icon"
  min_sdk_android: 21

  ios: true
  remove_alpha_ios: true
  image_path_ios_dark_transparent: "assets/icons/primary/calibrateFullDark.png"

  web:
    generate: true
    image_path: "assets/icons/primary/calibrate.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

  windows:
    generate: true
    image_path: "assets/icons/primary/calibrate.png"
    icon_size: 48

  macos:
    generate: true
    image_path: "assets/icons/primary/calibrate.png"