// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNgAqQLkv6DZCGYMzX6Pw_ac11JMGFx9s',
    appId: '1:713888861074:web:83d64dfccb7e1773a34f4b',
    messagingSenderId: '713888861074',
    projectId: 'calibratecpa',
    authDomain: 'calibratecpa.firebaseapp.com',
    storageBucket: 'calibratecpa.firebasestorage.app',
    measurementId: 'G-K2NPNJK2LX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrL_rX2xT9KZQm19mIEo5wM04DuBIV_Tw',
    appId: '1:713888861074:android:a900392d7a5ee5e9a34f4b',
    messagingSenderId: '713888861074',
    projectId: 'calibratecpa',
    storageBucket: 'calibratecpa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-NoWBQT3mLWWvDejmWQRvFH3PJiyd2xc',
    appId: '1:713888861074:ios:8f310f32936cd360a34f4b',
    messagingSenderId: '713888861074',
    projectId: 'calibratecpa',
    storageBucket: 'calibratecpa.firebasestorage.app',
    iosBundleId: 'com.calebh101.calibratecpa',
  );

}